#!/usr/bin/env node
/**
 * Extract HTTP methods from grammar.js and generate lua/poste-http/http/_methods.lua
 *
 * This is the single source of truth: grammar.js defines the methods,
 * and this script propagates them to the Lua completion data.
 *
 * Usage: node tools/extract-methods.js [--check]
 *   --check  Exit non-zero if generated file is stale (CI use)
 */

const fs = require("fs");
const path = require("path");

const GRAMMAR = path.join(__dirname, "..", "grammar.js");
const LUA_OUT = path.join(__dirname, "..", "..", "lua", "poste-http", "http", "_methods.lua");

function extractMethods(source) {
  const methods = [];
  const re = /method_(\w+):\s*\$ =>\s*'(\w+)'/g;
  let match;
  while ((match = re.exec(source)) !== null) {
    methods.push(match[2]);
  }
  return methods.sort();
}

function generateLua(methods) {
  const lines = methods.map((m) => `  "${m}",`);
  return `--- AUTO-GENERATED by tree-sitter-poste-http/tools/extract-methods.js
--- DO NOT EDIT. Run: npm run generate-data (in tree-sitter-poste-http/)
--- Source of truth: grammar.js

return {
${lines.join("\n")}
}
`;
}

function main() {
  const grammar = fs.readFileSync(GRAMMAR, "utf8");
  const methods = extractMethods(grammar);
  const lua = generateLua(methods);

  if (process.argv.includes("--check")) {
    const existing = fs.existsSync(LUA_OUT) ? fs.readFileSync(LUA_OUT, "utf8") : "";
    if (existing !== lua) {
      console.error("_methods.lua is stale. Run `npm run generate-data` in tree-sitter-poste-http/");
      process.exit(1);
    }
    console.log("_methods.lua is up-to-date");
    process.exit(0);
  }

  fs.mkdirSync(path.dirname(LUA_OUT), { recursive: true });
  fs.writeFileSync(LUA_OUT, lua);
  console.log(`Generated ${LUA_OUT} (${methods.length} methods)`);
}

main();