--- AUTO-GENERATED by tree-sitter-poste-http/tools/extract-methods.js
--- DO NOT EDIT. Run: npm run generate-data (in tree-sitter-poste-http/)
--- Source of truth: grammar.js

return {
  "CONNECT",
  "DELETE",
  "GET",
  "HEAD",
  "OPTIONS",
  "PATCH",
  "POST",
  "PUT",
  "SCRIPT",
  "TRACE",
}
